/**
 * Parses the authorization URL generated by PKCE providers to extract the `key` parameter 
 * and the clean `AuthUrl` (without the key parameter).
 * 
 * @param {string} url - The full authorization URL generated by a provider's `getAuthorizationUrl()`.
 * @returns {{ key: string; AuthUrl: string }} An object containing the extracted `key` and the clean `AuthUrl`.
 * 
 * @example
 * ```typescript
 * const fullUrl = google.getAuthorizationUrl();
 * const { key, AuthUrl } = ExtractKey(fullUrl) as { key: string; AuthUrl: string };
 * // Save `key` to session/cookie and redirect user to `AuthUrl`
 * ```
 */
export function ExtractKey(url :string):unknown {
    let key : string | undefined = undefined
    url.split('?')[1].split('&').forEach((elm)=> {
        const elmkey : string[] = elm.split('=')
        if(elmkey[0] == 'key'){
            key = elmkey[1]
        }
    })
    const AuthUrl = url.split('&').slice(0,-1).join('&')
    return {key , AuthUrl}
}